---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: Sample-eks4
  region: ap-south-1
  version: "1.23"
availabilityZones:
- ap-south-1a
- ap-south-1b
managedNodeGroups:
- name: managed-nodes
  labels:
    role: managed-nodes
  instanceType: t2.medium
  minSize: 1
  maxSize: 10
  desiredCapacity: 2
  volumeSize: 20
    #nodeGroups:
    #- name: unmanaged-nodes
    #  labels:
    #    role: unmanaged-nodes
    #  instanceType: t2.medium
    #  minSize: 1
    #  maxSize: 10
    #  desiredCapacity: 1
    #  volumeSize: 20
