---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: Sample-eks3
  region: ap-south-1
  version: "1.20"
availabilityZones:
- ap-south-1a
- ap-south-1b
managedNodeGroups:
- name: ng-1
  labels:
    role: ng-1
  instanceType: t2.medium
  minSize: 1
  maxSize: 10
  desiredCapacity: 1
  volumeSize: 20
- name: ng-2
  labels:
    role: ng-2
  instanceType: t2.medium
  minSize: 1
  maxSize: 10
  desiredCapacity: 1
  volumeSize: 20
