apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
 
metadata:
 name: non-prod-eks-cluster1
 region: us-east-1
 
vpc:
 id: "vpc-0912ec40f8e4c54fc"
 subnets:
   private:
     us-east-1a:
         id: "subnet-0e768b8834950decf"
     us-east-1b:
         id: "subnet-0d7ec2a9445ac2860"
   public:
     us-east-1a:
         id: "subnet-0c0685f6f3f2d4163"
     us-east-1b:
         id: "subnet-04e8737dcff416fb9"

 
managedNodeGroups:
 - name: ng-1
   instanceType: t2.medium
   desiredCapacity: 2
   privateNetworking: true
   volumeSize: 20
   ssh:
     publicKeyName: eks
 - name: ng-2
   instanceType: t2.medium
   desiredCapacity: 2
   privateNetworking: true
   volumeSize: 20
   ssh:
     publicKeyName: eks
