apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ms-attendance-service-secrets
  namespace: eatos-nv-preprod
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "preprod/ms-attendance-service1"
          objectType: "secretsmanager"
          objectAlias: ".env.json"
